/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package visual;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author alain
 */
public class IntroducirDatos extends javax.swing.JDialog {

    /**
     * Creates new form IntroducirDatos
     */
    public IntroducirDatos(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon imageIcon = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/pexels-felix-mittermeier-956999.jpg"))); // load the image to a imageIcon
        Image image = imageIcon.getImage(); 
        Image newimg = image.getScaledInstance(jLabelFondo.getWidth(), jLabelFondo.getHeight(), Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);  
        jLabelFondo.setIcon(imageIcon);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelId = new javax.swing.JLabel();
        jTextFieldId = new javax.swing.JTextField();
        jTextFieldId1 = new javax.swing.JTextField();
        jLabelId1 = new javax.swing.JLabel();
        jLabelId2 = new javax.swing.JLabel();
        jTextFieldId2 = new javax.swing.JTextField();
        jTextFieldId3 = new javax.swing.JTextField();
        jTextFieldId4 = new javax.swing.JTextField();
        jLabelId3 = new javax.swing.JLabel();
        jLabelId4 = new javax.swing.JLabel();
        jLabelId5 = new javax.swing.JLabel();
        jTextFieldId5 = new javax.swing.JTextField();
        jTextFieldId6 = new javax.swing.JTextField();
        jLabelId6 = new javax.swing.JLabel();
        jLabelId7 = new javax.swing.JLabel();
        jTextFieldId7 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabelFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("CLASIFICACIÓN DE OBJETO ESTELAR");
        jPanel1.add(jLabelTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 420, 60));

        jLabelId.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId.setText("Identificador de objeto:");
        jPanel1.add(jLabelId, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, 20));
        jPanel1.add(jTextFieldId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 70, -1));
        jPanel1.add(jTextFieldId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 110, 70, -1));

        jLabelId1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId1.setText("Ascensión recta:");
        jPanel1.add(jLabelId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 90, 20));

        jLabelId2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId2.setText("Declinación:");
        jPanel1.add(jLabelId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 70, 20));
        jPanel1.add(jTextFieldId2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 70, -1));
        jPanel1.add(jTextFieldId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 70, -1));
        jPanel1.add(jTextFieldId4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 80, 70, -1));

        jLabelId3.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId3.setText("Corrimiento al rojo:");
        jPanel1.add(jLabelId3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 130, 20));

        jLabelId4.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId4.setText("Filtro ultravioleta*:");
        jPanel1.add(jLabelId4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 130, 20));

        jLabelId5.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId5.setText("Filtro de verde*:");
        jPanel1.add(jLabelId5, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 110, 130, 20));
        jPanel1.add(jTextFieldId5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 110, 70, -1));
        jPanel1.add(jTextFieldId6, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 170, 70, -1));

        jLabelId6.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId6.setText("Filtro de infrarrojo cercano*:");
        jPanel1.add(jLabelId6, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 170, 150, 20));

        jLabelId7.setForeground(new java.awt.Color(255, 255, 255));
        jLabelId7.setText("Filtro de infrarrojo*:");
        jPanel1.add(jLabelId7, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 150, 20));
        jPanel1.add(jTextFieldId7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 140, 70, -1));

        jButton1.setText("Aceptar");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, -1));

        jButton2.setText("Cancelar");
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jButton3.setText("Limpiar");
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, 80, -1));

        jLabelFondo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pexels-igor-mashkov-6325001.jpg"))); // NOI18N
        jLabelFondo.setText("Identifi");
        jPanel1.add(jLabelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 320));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IntroducirDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IntroducirDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IntroducirDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IntroducirDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                IntroducirDatos dialog = new IntroducirDatos(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabelFondo;
    private javax.swing.JLabel jLabelId;
    private javax.swing.JLabel jLabelId1;
    private javax.swing.JLabel jLabelId2;
    private javax.swing.JLabel jLabelId3;
    private javax.swing.JLabel jLabelId4;
    private javax.swing.JLabel jLabelId5;
    private javax.swing.JLabel jLabelId6;
    private javax.swing.JLabel jLabelId7;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldId;
    private javax.swing.JTextField jTextFieldId1;
    private javax.swing.JTextField jTextFieldId2;
    private javax.swing.JTextField jTextFieldId3;
    private javax.swing.JTextField jTextFieldId4;
    private javax.swing.JTextField jTextFieldId5;
    private javax.swing.JTextField jTextFieldId6;
    private javax.swing.JTextField jTextFieldId7;
    // End of variables declaration//GEN-END:variables
}
