/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visual;

import java.awt.Image;
import java.awt.Point;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.ImageIcon;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.TransferHandler;

/**
 *
 * @author alain
 */
public class Principal extends javax.swing.JFrame {
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        
        this.setUndecorated(true);
     
        initComponents();
        
        ImageIcon imageIcon = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/imagenes/pexels-pixabay-2150.jpg"))); // load the image to a imageIcon
        Image image = imageIcon.getImage(); 
        Image newimg = image.getScaledInstance(jMenuCerrar.getWidth(), jMenuCerrar.getHeight(), Image.SCALE_SMOOTH); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);  
        jMenuCerrar.setIcon(imageIcon);
        
        this.setLocationRelativeTo(null);

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jMenuCerrar = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuClasificar = new javax.swing.JMenu();
        jMenuItemIntroducirDatos = new javax.swing.JMenuItem();
        jMenuItemCargarDatosDesdeArchivo = new javax.swing.JMenuItem();
        jMenuInformacion = new javax.swing.JMenu();
        jMenuItem = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItemComoUsar = new javax.swing.JMenuItem();
        jMenuItemAcercaDe = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMenuCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, 576, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jMenuCerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 437, Short.MAX_VALUE)
        );

        jMenuClasificar.setText("Clasificar");
        jMenuClasificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuClasificarActionPerformed(evt);
            }
        });

        jMenuItemIntroducirDatos.setText("Introducir datos");
        jMenuItemIntroducirDatos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemIntroducirDatosActionPerformed(evt);
            }
        });
        jMenuClasificar.add(jMenuItemIntroducirDatos);

        jMenuItemCargarDatosDesdeArchivo.setText("Importar desde archivo");
        jMenuItemCargarDatosDesdeArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCargarDatosDesdeArchivoActionPerformed(evt);
            }
        });
        jMenuClasificar.add(jMenuItemCargarDatosDesdeArchivo);

        jMenuBar1.add(jMenuClasificar);

        jMenuInformacion.setText("Información");

        jMenuItem.setText("¿Qué es una estrella?");
        jMenuInformacion.add(jMenuItem);

        jMenuItem3.setText("¿Qué es una galaxia?");
        jMenuInformacion.add(jMenuItem3);

        jMenuItem2.setText("¿Qué es un cuásar?");
        jMenuInformacion.add(jMenuItem2);

        jMenuItem4.setText("¿Cómo se obtuvo el modelo de clasificación?");
        jMenuInformacion.add(jMenuItem4);

        jMenuBar1.add(jMenuInformacion);

        jMenuAyuda.setText("Ayuda");

        jMenuItemComoUsar.setText("Cómo usar la aplicación");
        jMenuAyuda.add(jMenuItemComoUsar);

        jMenuItemAcercaDe.setText("Acerca de la aplicación");
        jMenuItemAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAcercaDeActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItemAcercaDe);

        jMenuBar1.add(jMenuAyuda);

        jMenu1.setText("Cerrar");
        jMenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu1ActionPerformed(evt);
            }
        });

        jMenuItem1.setText("Salir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCargarDatosDesdeArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCargarDatosDesdeArchivoActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Seleccionar ubicación del archivo.");

        int seleccion = fileChooser.showSaveDialog(this);

        if (seleccion == JFileChooser.APPROVE_OPTION) {
            File archivo = fileChooser.getSelectedFile();
            String ruta = archivo.getAbsolutePath();

            try {
                
                BufferedReader br = new BufferedReader(new FileReader(archivo));
                
                String linea=br.readLine();
                
                String[] datos = linea.split(",");
                
                IntroducirDatos ventana=new IntroducirDatos(this, true);
                
                ventana.setTextFieldId(datos[0]);
                ventana.setTextFieldAscension(datos[1]);
                ventana.setTextFieldDeclinacion(datos[2]);
                ventana.setTextFieldCorrimiento(datos[3]);
                ventana.setTextFieldUltravioleta(datos[4]);
                ventana.setTextFieldVerde(datos[5]);
                ventana.setTextFieldInfrarrojo(datos[6]);
                ventana.setTextFieldInfrarrojoCercano(datos[7]);
                
                ventana.setLocationRelativeTo(null);
                
                ventana.habilitarAceptarAlCargar();
                ventana.setVisible(true);
                
               
                
            } catch (IOException e) {
               
            }
        }
    }//GEN-LAST:event_jMenuItemCargarDatosDesdeArchivoActionPerformed

    private void jMenuClasificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuClasificarActionPerformed

    }//GEN-LAST:event_jMenuClasificarActionPerformed

    private void jMenuItemIntroducirDatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemIntroducirDatosActionPerformed
        intD=new IntroducirDatos(this, true);
        intD.setLocationRelativeTo(null);
        intD.setResizable(false);
        intD.setVisible(true);
    }//GEN-LAST:event_jMenuItemIntroducirDatosActionPerformed

    private void jMenuItemAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAcercaDeActionPerformed
        AcercaDe acerca_de = new AcercaDe(this, true);
        acerca_de.setLocationRelativeTo(null);
        acerca_de.setVisible(true);
    }//GEN-LAST:event_jMenuItemAcercaDeActionPerformed

    private void jMenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu1ActionPerformed
        
    }//GEN-LAST:event_jMenu1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private IntroducirDatos intD;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel jMenuCerrar;
    private javax.swing.JMenu jMenuClasificar;
    private javax.swing.JMenu jMenuInformacion;
    private javax.swing.JMenuItem jMenuItem;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItemAcercaDe;
    private javax.swing.JMenuItem jMenuItemCargarDatosDesdeArchivo;
    private javax.swing.JMenuItem jMenuItemComoUsar;
    private javax.swing.JMenuItem jMenuItemIntroducirDatos;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
